name: Compilar e Testar Zoológico

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Verificar estrutura de arquivos
      run: |
        echo "Listando arquivos:"
        ls -R Zoologico

    - name: Compilar teste com implementação
      run: |
        gcc -I Zoologico/src \
            Zoologico/src/zoologico.c \
            Zoologico/teste/teste.c \
            -o unitario

    - name: Executar testes
      run: ./unitario
